Add support for C2B transaction simulation.
SmoDav/mpesa pull request #17
Opened 2018-01-21 15:31 UTC by swimlappy

Hello,

For consideration, I have added support for sending a C2B transaction simulation.  This is something that really helps during testing.  This is a fantastic package and would really like to see if this can be merged in.

Thank you!

2018-01-28 04:26 UTC, swimlappy commented
Hello, have you had a chance to review this pull request?  Thanks

2018-01-28 05:51 UTC, SmoDav requested changes

2018-01-28 05:51 UTC, SmoDav commented on README.md
> +    ->setCommand('CustomerPayBillOnline')
Add this to a constant. It's better to call `Simulate::CUSTOMER_PAYBILL_ONLINE`

2018-01-28 05:51 UTC, SmoDav commented on src/Mpesa/C2B/Simulate.php
> +
Also remove the validation as all characters are allowed.

2018-01-28 05:51 UTC, SmoDav commented on src/Mpesa/C2B/Simulate.php
> +        $valid_commands = ['CustomerPayBillOnline', 'CustomerBuyGoodsOnline'];
Add these commands as constants

2018-01-28 15:22 UTC, swimlappy commented
Hello, thanks for the review.  I've added in the changes that you have requested and added to this pull request.  Please let me know if these look good.  Thank you

2018-01-31 05:37 UTC, swimlappy commented
Hi, do the changes look ok to you?  Thanks

2018-02-08 18:44 UTC, swimlappy commented
Hello, have you had a chance to review the additional changes?  Thanks

2018-02-12 04:19 UTC, merged