Add setCommand for STK push and update config
SmoDav/mpesa pull request #32
Opened 2019-05-15 19:13 UTC by codingedward

#### What does this PR do?
This PR fixes two problems on the current codebase:
##### STK Push command ID
- Since STK push now supports both `CustomerPayBillOnline` and `CustomerBuyGoodsOnline` command IDs this PR will enable one to use `setCommand` when doing an STK push as shown below.
  ```php
   $response = STK::request(10)
     ->from(254722000000)
     ->usingAccount('paybill_2')
     ->usingReference('Some reference', 'Test payment')
     ->setCommand(CUSTOMER_PAYBILL_ONLINE)
     ->push();
  ```

##### Business Shortcode vs Paybill Number
- Safaricom distinguishes between the `Business Shortcode` and `Paybill Number` and therefore we would need a way to differentiate between the two on the configuration file as shown below.

```php
    'accounts' => [
        'staging' => [
            'sandbox' => true,
            'key' => '',
            'secret' => '',
            'initiator' => 'apitest363',
            'id_validation_callback' => 'http://example.com/callback?secret=some_secret_hash_key',
            'lnmo' => [
                'paybill' => 174379,
                'shortcode' => 174379,
                'passkey' => 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
                'callback' => 'http://example.com/callback?secret=some_secret_hash_key',
            ]
        ],
      ]
```
- Note that it is only for the testing/sandbox paybill the `Business Shortcode` and the `Paybill Number` happen to be the same (174379)

#### Background context
These changes on their API have, unfortunately, not been updated on their documentation and may cause a lot of frustration before one figures it out.

2019-05-16 06:40 UTC, SmoDav commented
And won't the STK push command always be `CustomerPayBillOnline`?

2019-05-16 07:17 UTC, codingedward commented
No they won't @SmoDav, Safaricom now supports using `CustomerBuyGoodsOnline` for STK Push too. 

I have been working on a project where I had to make this change on the package to support this change.

2019-05-16 08:04 UTC, SmoDav commented
In that case won't PartyB change depending on the command?

2019-05-16 08:58 UTC, codingedward commented
I will have to confirm this. 

If it will then I can simply provide a check to ensure we are setting the correct PartyB (based on the command).

I will get back to you on this.

2019-05-16 09:55 UTC, codingedward commented
@SmoDav, unfortunately, I have no way of validating this as my Paybill Account only supports using `CustomerBuyGoodsOnline`. 

The documentation provided by Safaricom also seems to be outdated and does not reflect these changes (including the one `CustomerBuyGoodsOnline`). 

Would it be possible to verify this on your end?

2019-05-20 09:52 UTC, codingedward commented
@SmoDav, any progress on this?

2019-05-20 10:41 UTC, SmoDav requested changes

2019-05-20 10:41 UTC, SmoDav commented on src/Mpesa/C2B/STK.php
> +    protected $command = null;
Have a default, `CustomerPayBillOnline`, for backward compatibility

2019-05-20 10:43 UTC, SmoDav commented
Have a check so that when the command is `CustomerPayBillOnline`,  `PartyB` is the shortcode.

2019-05-21 18:55 UTC, codingedward commented on src/Mpesa/C2B/STK.php
> +    protected $command = null;
That makes sense... on it 👍

2019-05-21 18:56 UTC, codingedward commented
Sure, will do 👍

2019-05-21 19:12 UTC, codingedward commented
@SmoDav, I have made the necessary changes. Kindly review.

2019-05-22 05:33 UTC, SmoDav requested changes

2019-05-22 05:33 UTC, SmoDav commented on src/Mpesa/C2B/STK.php
> +    public function push($amount = null, $number = null, $reference = null, $command = null, $description = null, $account = null)
Move the command and make it the last arguement for backward compatibility.

2019-05-22 05:33 UTC, SmoDav commented on README.md
> +    ->setCommand(CUSTOMER_PAYBILL_ONLINE)
state this as being optional

2019-05-22 05:33 UTC, SmoDav commented on README.md
> +$response = $stk->push(10, 254722000000, 'some reference', CUSTOMER_PAYBILL_ONLINE, 'Test Payment');
move the `CUSTOMER_PAYBILL_ONLINE` to be the last argument and also state that it's optional, giving a default of  `CustomerPayBillOnline`

2019-05-22 05:33 UTC, SmoDav commented on README.md
> +$response = $stk->push(10, 254722000000, 'some reference', CUSTOMER_PAYBILL_ONLINE, 'Test Payment', 'paybill_2');
same as above

2019-05-22 05:33 UTC, SmoDav commented on README.md
> +$response = STK::push(10, 254722000000, 'some reference', CUSTOMER_PAYBILL_ONLINE, 'Test Payment');
same as above

2019-05-22 08:38 UTC, codingedward commented
@SmoDav, I've implemented the changes, thanks for your review.

Lastly, I've realized that in order to preserve backwards-compatibility we might cause a bit of confusion to the end users due to arguments ordering when using `Simulate` and `STK`.

In the case of `Simulate`, we have:
`push(amount = null, number = null, reference = null, command = null, account = null)`

While using `STK`, we have:
`push(amount = null, number = null, reference = null, description = null, account = null, command = null)`

Notice the order of the `account` and the `command` parameters. Should we preserve backwards-compatibility at the expense of having the order different, or should we go ahead and swap them?

I'd appreciate your view on this 🥂

2019-05-22 10:16 UTC, SmoDav commented
I assumed that you would change all the new parameters to be the last parameter 😄

2019-05-22 10:59 UTC, codingedward commented
Okay, that makes sense... I'll do that.

2019-05-22 12:40 UTC, codingedward commented
Hello @SmoDav, I've just made the update. For consistency, I have also set the default command for `Simulate` to be `CustomerPaybillOnline` too.

I believe this is ready now.

2019-05-22 16:49 UTC, merged